Added timing signal text filtering to QT Gui
mp3guy/Stopwatch pull request #12
Opened 2023-11-15 00:59 UTC by dbarnes

Allow filtering signals by text
This filter also applies to the plot all / none buttons
Not that QT familiar so happy for advice on different approaches to this

2023-11-15 16:03 UTC, dbarnes commented
(pending further update)

2023-11-15 21:20 UTC, mp3guy requested changes
Waiting for changes

2024-05-11 16:52 UTC, dbarnes commented
Gave this one another go
- case insensitive text filter
- extra buttons for adding / removing only the filtered entries to the plot
- made the columns sortable (by clicking the headers)
- That way you can easily filter then click to sort by the slowest functions (for example)
- The default sorting on launch is ascending name

<img width="1136" alt="Screenshot 2024-05-11 at 09 36 47" src="https://github.com/mp3guy/Stopwatch/assets/5920715/f7598ce3-d0aa-4af5-8406-20e14b437b97">
<img width="1136" alt="Screenshot 2024-05-11 at 09 37 43" src="https://github.com/mp3guy/Stopwatch/assets/5920715/ff8ca1d0-7146-4699-a5b5-3a771d746f39">
<img width="1136" alt="Screenshot 2024-05-11 at 09 51 10" src="https://github.com/mp3guy/Stopwatch/assets/5920715/4ada98c5-b433-4bbe-a5c9-9ed52c0ed266">

2024-05-15 18:47 UTC, mp3guy approved these changes

2024-05-15 18:47 UTC, merged